const fs = require("fs")
const vm = require("vm")
const assert = require("assert")

const source = fs.readFileSync("Model.js", "utf8").replace(/^\.pragma library\s*/, "")
const context = {}
vm.createContext(context)
vm.runInContext(source, context)

assert.strictEqual(context.BAND_COUNT, 21)
assert.strictEqual(context.normalizeBands([]).length, 21)
assert.strictEqual(context.normalizeBands([-1, 0.5, 9])[0], 0)
assert.strictEqual(context.normalizeBands([-1, 0.5, 9])[1], 0.5)
assert.strictEqual(context.normalizeBands([-1, 0.5, 9])[2], 1)
assert.strictEqual(context.formatClock(0), "0:00")
assert.strictEqual(context.formatClock(65), "1:05")
assert.strictEqual(context.formatClock(3661), "1:01:01")
assert.strictEqual(context.bandLabel("climate_energy"), "CLIMATE / ENERGY")
assert.strictEqual(context.rangeLabel("30"), "30D")
assert.strictEqual(context.rangeLabel("2026"), "2026")
assert.strictEqual(context.rangeLabel("2026-08-29"), "2026-08-29")
assert.strictEqual(context.filterLabel("any"), "ANY TIME")
assert.strictEqual(context.filterLabel("7"), "LAST 7 DAYS")
assert.strictEqual(context.filterLabel("30"), "LAST 30 DAYS")
assert.strictEqual(context.filterLabel("2026"), "ANY TIME")
assert.strictEqual(context.compactSignal([], false), "─────")
assert.strictEqual(context.compactSignal(Array(21).fill(0), true), "▁▁▁▁▁")
assert.strictEqual(context.compactSignal(Array(21).fill(1), true), "█████")
assert.strictEqual(context.playbackLabel("loading"), "TUNING")
assert.strictEqual(context.progress(25, 100), 0.25)
assert.strictEqual(context.progress(200, 100), 1)
assert.strictEqual(context.progress(1, 0), 0)
assert.strictEqual(context.parsePlaybackStatus('{"playback":"playing","position":12,"duration":60,"volume":70}').position, 12)
assert.strictEqual(context.parsePlaybackStatus('{"playback":"unknown"}'), null)
assert.strictEqual(context.parsePeople('[{"value":"Lyn_Alden","label":"Lyn Alden"}]')[0].label, "Lyn Alden")
assert.strictEqual(context.parsePeople("not json"), null)
assert.strictEqual(context.parseEpisodeList('[{"audioUrl":"https://example.test/a.mp3","title":"Saved"}]')[0].title, "Saved")
assert.strictEqual(context.parseEpisodeList('[{"title":"Missing URL"}]').length, 0)
assert.strictEqual(context.parseEpisodeList("not json"), null)
assert.strictEqual(context.parseSpectrum(JSON.stringify(Array(21).fill(0.5))).length, 21)
assert.strictEqual(context.parseSpectrum(JSON.stringify(Array(20).fill(0.5))), null)
assert.strictEqual(context.parseEpisode('{"title":"Episode","audioUrl":"https://example.test/a.mp3"}').title, "Episode")
assert.strictEqual(context.parseEpisode("not json"), null)

console.log("model tests: ok")
